import * as l10n from '@vscode/l10n';

export interface WalkthroughMarkdownBlock {
  label: string;
  startLine: number;
  endLine: number;
  description?: string;
  explanation?: string;
  annotations?: { line: number; text: string }[];
}

export function buildWalkthroughMarkdown(
  filePath: string,
  symbolName: string,
  overview: string,
  blocks: WalkthroughMarkdownBlock[],
): string {
  const lines: string[] = [];
  const now = new Date().toLocaleString('en-US', { timeZone: 'UTC' });

  lines.push(l10n.t('# {0} — Walkthrough', symbolName));
  lines.push('');
  lines.push(`> ${l10n.t('**File**: `{0}`  ', filePath)}`);
  lines.push(`> ${l10n.t('**Generated**: {0}  ', now)}`);
  lines.push(`> ${l10n.t('*Auto-generated by CodeWalker*')}`);
  lines.push('');
  lines.push(l10n.t('## Overview'));
  lines.push('');
  lines.push(overview);
  lines.push('');

  lines.push(l10n.t('## Block List'));
  lines.push('');
  for (let index = 0; index < blocks.length; index++) {
    const block = blocks[index];
    const anchor = `block-${index + 1}`;
    lines.push(`${index + 1}. [${block.label}](#${anchor}) (L${block.startLine}-L${block.endLine})${block.description ? ' — ' + block.description : ''}`);
  }
  lines.push('');
  lines.push('---');
  lines.push('');

  for (let index = 0; index < blocks.length; index++) {
    const block = blocks[index];

    lines.push(`<a id="block-${index + 1}"></a>`);
    lines.push(`### ${index + 1}. ${block.label}`);
    lines.push('');
    lines.push(l10n.t('**Range**: L{0}–L{1}', String(block.startLine), String(block.endLine)));
    if (block.description) {
      lines.push('  ');
      lines.push(l10n.t('**Description**: {0}', block.description));
    }
    lines.push('');

    if (block.annotations && block.annotations.length > 0) {
      lines.push(l10n.t('**Line Annotations**:'));
      lines.push('');
      for (const annotation of block.annotations) {
        lines.push(`- L${annotation.line}: ${annotation.text}`);
      }
      lines.push('');
    }

    if (block.explanation) {
      lines.push(l10n.t('#### Explanation'));
      lines.push('');
      lines.push(block.explanation);
      lines.push('');
    }

    if (index < blocks.length - 1) {
      lines.push('---');
      lines.push('');
    }
  }

  return lines.join('\n');
}